Repository zim-desktop-wiki/zim-desktop-wiki, pull requests merged in 2020-06, with the labels that each got.

#1062 Partial rewrite of Help/Config_Files.txt
  data/manual/Help/Config_Files.txt
Labels: documentation, fix available

#1058 Describe installation from Homebrew for Mac OS X
  README.md
  website/files/images/os-apple.png
  website/pages/downloads.txt
Labels: documentation, fix available

#1051 distraction free editing plugin: remove all colors of the window chrome
  zim/plugins/distractionfree.py
Labels: enhancement, fix available

#1009 Fix crash when toggle_on_altspace=True
  zim/gui/mainwindow.py
Labels: bug, fix available

#1029 Give temporary directories unique names
  zim/fs.py
Labels: enhancement, fix available

#1008 Macos integration
  data/manual/Plugins.txt
  data/manual/Plugins/macOS_Menubar.txt
  zim.py
  zim/gui/uiactions.py
  zim/main/__init__.py
  zim/plugins/osx_menubar.py
Labels: enhancement, fix available

#996 Evaluate TEXTDOMAINDIR to set locale directory
  zim/__init__.py
Labels: enhancement, fix available

#933 Fix export issue and a typo in Plugin sourceview
  zim/plugins/sourceview.py
Labels: fix available

#808 Improve find bar behaviour (fixes #317 and #128)
  zim/gui/pageview.py
Labels: fix available, usability

#802 Swap order of the format and calendar panels
  zim/gui/pageview.py
Labels: fix available, usability
